### ISSUE TITLE
Use `track_latest` attribute for the `aws_ecs_task_definition` resource at `service` module

### ISSUE THREAD

**Issue by ivan-sukhomlyn** [terraform-aws-modules/terraform-aws-ecs#169] opened 2024-02-16 17:40 UTC
## Is your request related to a new offering from AWS?
The `track_latest` attribute for the `aws_ecs_task_definition` resource released in in [v5.37.0 of the Terraform AWS Provider](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.37.0)

Related PR - https://github.com/hashicorp/terraform-provider-aws/pull/30154

## Is your request related to a problem?
Simplify the `service` module source code and pass sorting of ECS Taks Definition revisions to the Terraform provider.

## Describe the solution you'd like.
Use the `track_latest = true` argument at the `aws_ecs_task_definition` instead of a custom implementation
https://github.com/terraform-aws-modules/terraform-aws-ecs/blob/8b97783def49997d18a6fcb00dc21ce1edc0f538/modules/service/main.tf#L589-L608

## More Details
An appropriate GH issue - https://github.com/hashicorp/terraform-provider-aws/issues/20121

**Comment by ivan-sukhomlyn** [comment] 2024-02-16 17:43
@antonbabenko @bryantbiggs I can make a PR to the [wip/v6](https://github.com/terraform-aws-modules/terraform-aws-ecs/tree/wip/v6) branch if you are ok with that activity.
Thanks!

**Comment by bryantbiggs** [comment] 2024-02-16 19:41
yes please do - closing this issue though since its a duplicate of #164

**Closed by bryantbiggs** 2024-02-16 19:41 UTC
